#端口
server:
  port: 8080
  servlet:    context-path: /
spring:
  #数据源
  application:    name: generator
    
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
      username: root
      password: 123456
      filters: stat,wall,log4j2,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  #请求
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
  #资源
  resources:
    static-locations: classpath:/static
  #redis
  redis:
    database: 0 
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 10 
mybatis:
  mapper-locations: com/tools/demo/*/dao/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
#日志
logging:
  config: classpath:log4j2.yml
eureka:
  instance:
    home-page-url: /html
  client:
    serviceUrl:
      defaultZone: http://lzx:123456@localhost:1000/lzx/eureka/
    healthcheck:      enabled: true
management:  endpoint:    health:      show-details: always
    info:      enabled: true
